services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BokuNo\YABT\:
    resource: '../Classes/*'

  BokuNo\YABT\Controller\ThemeController:
    tags: ['backend.controller']
